//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment5_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENTprofile
    {
        public int Rollno { get; set; }
        public string Name { get; set; }
        public System.DateTime Dateof { get; set; }
        public string Gender { get; set; }
        public string Department { get; set; }
        public string Course { get; set; }
        public string Semester { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public int Id { get; internal set; }
    }
}
